openapi: 3.0.0
info:
  title: OnboardingAPI
  description: STD22070
  version: 1.3.0
servers:
  - url: http://std22070.com
paths:
  /students:
    get:
      tags:
        - students
      responses:
        '200':
          description: Successfully get all students
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    birthdate:
                      type: string
        '500':
          description: Internal server error
    post:
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                id:
                  type: integer
                name:
                  type: string
                birthdate:
                  type: string
      responses:
        '200':
          description: Successfully added your student
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  birthdate:
                    type: string
        '500':
          description: Internal server error
