openapi: 3.0.0
info:
  title: OnboardingAPI
  description: STD22070
  version: 1.3.0
servers:
  - url: http://std22070.com
paths:
  /students:
    get:
      summary: Get a list of all students
      tags:
        - students
      responses:
        '200':
          description: Successfully get all students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
    post:
      summary: Create a new student
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successfully added your student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
  /students/{studentId}:
    parameters:
      - in: path
        name: studentId
        schema:
          type: integer
        required: true
        description: ID of the student
        example: 1
    put:
      summary: Modify a student
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
    delete:
      summary: Delete a student by its ID
      tags:
        - students
      responses:
        '200':
          description: Successfully deleted student
        '500':
          description: Internal server error
  /teachers:
    get:
      summary: Get the list of teachers with their courses
      tags:
        - teachers
      responses:
        '200':
          description: Successfully get all teachers with their courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Teacher'
        '500':
          description: Internal server error
    post:
      summary: Add a new teacher
      tags:
        - teachers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Teacher'
      responses:
        '200':
          description: Successfully added a teacher
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
        '500':
          description: Internal server error
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Tanjona Andriantsitohaina
        birthdate:
          type: string
          example: 2005-10-27
    Teacher:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: Tokimahery
        lastName:
          type: string
          example: Ramarozaka
        courses:
          type: array
          items:
            $ref: '#/components/schemas/Course'
    Course:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        code:
          type: string
      example:
        - id: 1
          name: Algorithmique
          code: PROG1
        - id: 2
          name: Intéractions Homme-Machine
          code: IHM1
        - id: 3
          name: Bases de données relationnelles
          code: DONNEES1