openapi: 3.0.0
info:
  title: OnboardingAPI
  description: STD22070
  version: 1.3.0
servers:
  - url: http://std22070.com
paths:
  /students:
    get:
      responses:
        '200':
          description: Successfully get all students
        '500':
          description: Internal server error