openapi: 3.0.0
info:
  title: OnboardingAPI
  description: STD22070
  version: 1.3.0
servers:
  - url: http://std22070.com
paths:
  /students:
    get:
      summary: Get a list of all students
      tags:
        - students
      responses:
        '200':
          description: Successfully get all students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
    post:
      summary: Create a new student
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successfully added your student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
  /students/{studentId}:
    parameters:
      - in: path
        name: studentId
        schema:
          type: integer
        required: true
        description: ID of the student
    put:
      summary: Modify a student
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Internal server error
    delete:
      summary: Delete a student by its ID
      tags:
        - students
      responses:
        '200':
          description: Successfully deleted student
        '500':
          description: Internal server error
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthdate:
          type: string